### ISSUE TITLE
Installation link is private

### ISSUE THREAD

**Issue by brianegge** [klinquist/SunsetActionTile#1]
>  Sorry, this sub-forum is private.
> We cannot show you this page, because you don't have permission. Please try a different Forum or Knowledge Base selection.
> 
> 
> If you believe you should have access, please contact the Support Helpdesk.

**Comment by klinquist** [comment]
You may have to sign up for the AT forum.

**Comment by klinquist** [comment]
I went ahead and added more details to the readme.
